import { BranchOffice, Certification, EVehicleModel, ProductItem } from '../types';

export const COMPANY_INFO = {
  name: 'SoftTouch Sales & Services',
  brandName: 'SoftTouch™',
  tagline: 'Touch Of Modern Technology',
  motto: 'We Provide The Machineries',
  womensMotto: "Happy Women's - Some One Like Your Smile",
  personInCharge: 'Prof. Uday Motiram Yeshe',
  personInChargeTitle: 'Founder & Proprietor',
  partner: 'Vishnu Pralhad Khaire',
  primaryPhone: '+91 9096000080',
  secondaryPhone: '+91 9970022077',
  phones: ['+91 9096000080', '+91 9970022077', '+91 7350092004', '+91 7420032078', '+91 7420922077'],
  email: 'softtouchjalgaon2018@gmail.com',
  website: 'www.softtouchjalgaon.com',
  foundedYear: 2016,
  incorporationDate: '04 June 2019',
  gstin: '27AJPPY8167L1ZY',
  trademarkNo: '4226742 (Class 7)',
  msmeNo: 'MH14B0025106',
  gemStatus: 'Registered Government E-Marketplace Vendor',
  isoCert: 'ISO 9001:2015 Certified',
  ceCert: 'CE Compliance (Machinery Directive 2006/42/EC)',
  gmpCert: 'GMP Certified (Euro UK Standards)',
  employeesCount: '50+',
  businessOrganization: '10',
  factoryAddress: 'Ajantha Road, Opp. Manraj Maruti Showroom, M.I.D.C. Area, Jalgaon - 425003 (Maharashtra)',
  registeredAddress: 'Plot No. 13, Beside Puja Apartment, Near Girna Taki, Ramanand Nagar Road, Jalgaon - 425001 (MH)',
  branch1Address: 'Plot No. 21, Vidyut Colony, Jalgaon - 425001 (MH)',
  branch2Address: 'Plot No. 15, Shiv Colony, National Highway, Jalgaon - 425001 (MH)',
  golaniOffice: 'D-28, 2nd Floor, Golani Market, Jalgaon - 425001 (MH)',
  aganthaOffice: 'G-5/1, Ajantha Road, Opp. Manraj Maruti Showroom, M.I.D.C. Area, Jalgaon - 425003 (MH)'
};

export const CERTIFICATIONS_LIST: Certification[] = [
  {
    srNo: 1,
    particulars: 'ISO 9001:2015 Quality Management System',
    particularsMr: 'आयएसओ ९००१:२०१५ गुणवत्ता व्यवस्थापन प्रणाली',
    issuingAuthority: 'ARS Assessment & Estral Management (UAF / IAF / ABAS Accredited)',
    date: '17/07/2019 & 01/10/2022',
    certificateNo: '0719QMS3409 / 011022019101',
    validUntil: '30/09/2025',
    scope: 'Manufacture of Machines, Tools and Services',
    verificationLink: 'https://www.arscert.com',
    category: 'Quality'
  },
  {
    srNo: 2,
    particulars: 'CE Certificate of Compliance (Machinery Directive 2006/42/EC)',
    particularsMr: 'सीई अनुपालन प्रमाणपत्र (यंत्रसामग्री निर्देश २००६/४२/ईसी)',
    issuingAuthority: 'QVA Certification / GAAFS.US (Washington D.C., USA)',
    date: '01/10/2022',
    certificateNo: 'QVA-FLHV-22-0115569',
    validUntil: '30/09/2025',
    scope: 'Manufacture of Machines, Tools and Services',
    verificationLink: 'https://www.gaafs.us',
    category: 'Quality'
  },
  {
    srNo: 3,
    particulars: 'GMP - Good Manufacturing Practice',
    particularsMr: 'जीएमपी - उत्तम उत्पादन सराव प्रमाणपत्र',
    issuingAuthority: 'EURO.UK International Standard (ISC Accredited)',
    date: '01/10/2022',
    certificateNo: 'GMP/092020/13500',
    validUntil: '30/09/2025',
    scope: 'Manufacture of Machines, Tools and Services',
    category: 'Quality'
  },
  {
    srNo: 4,
    particulars: 'Registered Trademark (Class 7)',
    particularsMr: 'नोंदणीकृत ट्रेडमार्क (वर्ग ७)',
    issuingAuthority: 'Government of India, Trade Marks Registry, Mumbai',
    date: '05/07/2019',
    certificateNo: '4226742 (Form RG-2)',
    validUntil: '10 Years (Renewable)',
    scope: 'Machines and machine tools; motors & engines; incubators; agricultural implements',
    category: 'Legal'
  },
  {
    srNo: 5,
    particulars: 'Goods and Services Tax (GST) Registration',
    particularsMr: 'वस्तू व सेवा कर (जीएसटी) नोंदणी प्रमाणपत्र',
    issuingAuthority: 'Maharashtra State Government GST Department & Govt. of India',
    date: '31/03/2021',
    certificateNo: '27AJPPY8167L1ZY',
    scope: 'Proprietorship - Uday Motiram Yeshe, Jalgaon',
    category: 'Legal'
  },
  {
    srNo: 6,
    particulars: 'MSME / SSI Udyog Aadhar Registration',
    particularsMr: 'एमएसएमई / उद्योग आधार नोंदणी',
    issuingAuthority: 'Ministry of MSME, Government of India',
    date: '04/08/2018',
    certificateNo: 'MH14B0025106',
    scope: 'Micro, Small & Medium Enterprise Manufacturing',
    category: 'Government'
  },
  {
    srNo: 7,
    particulars: 'GeM - Government e-Marketplace Registration',
    particularsMr: 'जीईएम - शासकीय ई-मार्केटप्लेस नोंदणी',
    issuingAuthority: 'GeM (Govt. of India E-Marketplace)',
    date: '10/06/2019',
    certificateNo: 'Registered Approved Vendor',
    scope: 'Eligible for Government, Municipal & Institutional Tenders',
    category: 'Government'
  },
  {
    srNo: 8,
    particulars: 'Shop Act License',
    particularsMr: 'शॉप ॲक्ट परवाना',
    issuingAuthority: 'Labour Department, Government of Maharashtra',
    date: '04/08/2018',
    certificateNo: '1820800312288823',
    category: 'Legal'
  },
  {
    srNo: 9,
    particulars: 'Labour Contract License',
    particularsMr: 'कामगार कंत्राट परवाना',
    issuingAuthority: 'Labour Department, Government of Maharashtra',
    date: '28/08/2019',
    certificateNo: '13582190008306 (Applied / Registered)',
    category: 'Legal'
  },
  {
    srNo: 10,
    particulars: 'Permanent Account Number (PAN)',
    particularsMr: 'पॅन कार्ड नोंदणी',
    issuingAuthority: 'Income Tax Department, Government of India',
    date: '2009',
    certificateNo: 'Government Registered PAN',
    category: 'Legal'
  }
];

export const E_VEHICLES_DATA: EVehicleModel[] = [
  {
    id: 'food-truck',
    name: 'YES Food Truck (Commercial E-Cart)',
    nameMr: 'येस फूड ट्रक (व्यावसायिक ई-कार्ट)',
    contactNumber: '+91 7350092004',
    dimensions: '4 Foot x 6 Foot (Customizable / बदलता येऊ शकते)',
    loadCapacity: '500 kg',
    motor: '48V 1000W DC High Torque',
    battery: '12V 100Ah (Set of 4 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '48V 10A Heavy Duty Fast Charger',
    material: 'Mild Steel (MS) & Grade-304 Stainless Steel (SS)',
    range: '90 to 100 km per single charge',
    speed: '25 km/h',
    idealFor: 'Mobile restaurants, street food, snacks, tea, breakfast & fast food catering.',
    idealForMr: 'फिरते खाद्यपदार्थ केंद्र, चहा नाष्टा, स्ट्रीट फूड आणि जलद उपाहारगृह व्यवसाय.',
    badge: 'Best Seller'
  },
  {
    id: 'cold-drink-truck',
    name: 'YES Cold Drink Truck (High Payload & Speed)',
    nameMr: 'येस कोल्ड ड्रिंक ट्रक (जास्त वजन क्षमता व गती)',
    contactNumber: '+91 7420032078',
    dimensions: '4 Foot x 6 Foot (Customizable)',
    loadCapacity: '600 kg (Heavy Duty Chasis)',
    motor: '60V 1200W DC Heavy-Duty High Performance',
    battery: '12V 100Ah (Set of 5 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '60V 10A Heavy Duty Charger',
    material: 'Mild Steel & Stainless Steel insulated body',
    range: '90 to 100 km per charge',
    speed: '50 km/h (Top Speed Model)',
    idealFor: 'Beverages, ice cream, sugarcane juice, cold storage dairy delivery & bottled drinks.',
    idealForMr: 'शीतपेये, आईस्क्रीम, उसाचा रस, दूध वितरण आणि थंड साठवणूक व्यवसाय.',
    badge: 'High Speed 50 km/h'
  },
  {
    id: 'fruits-truck',
    name: 'YES Fruits & Fresh Produce Truck',
    nameMr: 'येस फळे व भाजीपाला विक्री ई-ट्रक',
    contactNumber: '+91 7420922077',
    dimensions: '3 Foot x 4 Foot (Compact for Narrow Streets / गल्ल्यांसाठी सोयीस्कर)',
    loadCapacity: '200 kg',
    motor: '48V 600W DC Economical Motor',
    battery: '12V 100Ah (Set of 4 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '48V 10A Smart Charger',
    material: 'MS & Stainless Steel Wire Mesh & Deck',
    range: '90 to 100 km per charge',
    speed: '25 km/h',
    idealFor: 'Daily fresh fruits, organic farm produce, tender coconut vending & doorstep delivery.',
    idealForMr: 'ताजी फळे, भाजीपाला, नारळ पाणी आणि घरोघरी थेट शेतमाल विक्रीसाठी आदर्श.',
    badge: 'Compact & Maneuverable'
  },
  {
    id: 'multiuse-truck',
    name: 'YES Multiuse Commercial Truck',
    nameMr: 'येस बहुउद्देशीय व्यावसायिक ई-ट्रक',
    contactNumber: '+91 7350092004',
    dimensions: '4 Foot x 6 Foot (Customizable Canopy/Shelves)',
    loadCapacity: '500 kg',
    motor: '48V 1000W DC',
    battery: '12V 100Ah (Set of 4 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '48V 10A',
    material: 'MS & High Tensile Stainless Steel',
    range: '90 to 100 km per charge',
    speed: '25 km/h',
    idealFor: 'General cargo, retail goods, textiles, hardware delivery, bakery items and local transit.',
    idealForMr: 'किराणा, कापड, बेकरी, हार्डवेअर मालवाहतूक आणि स्थानिक पुरवठा व्यवसाय.',
    badge: 'All-Rounder'
  },
  {
    id: 'marketing-truck',
    name: 'YES Marketing & Awareness Truck (जनजागृती अभियान)',
    nameMr: 'येस जनजागृती व मार्केटिंग अभियान ई-वाहन',
    contactNumber: '+91 9096000080',
    dimensions: '4 Foot x 6 Foot (Display Banners & Audio Mount)',
    loadCapacity: '300 kg',
    motor: '48V 850W DC Motor',
    battery: '12V 100Ah (Set of 4 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '48V 10A + 48V 10A (Dual Charger Support)',
    material: 'MS & Stainless Steel Frame with Public Address Panels',
    range: '90 to 100 km per charge',
    speed: '25 km/h',
    idealFor: 'Municipal announcements, health awareness campaigns, brand promotions & political rallies.',
    idealForMr: 'महानगरपालिका घोषणा, आरोग्य जनजागृती मोहिमा, जाहिरात व प्रचार मोहिमा.',
    badge: 'Govt. & Campaign Special'
  },
  {
    id: 'roaming-office',
    name: 'YES Roaming Office & Mobile Desk Vehicle',
    nameMr: 'येस रोमींग ऑफिस (फिरते कार्यालय ई-वाहन)',
    contactNumber: '+91 9096000080',
    dimensions: '4 Foot x 6 Foot (Custom Office Desk & Power Point)',
    loadCapacity: '500 kg',
    motor: '48V 600W DC Silent Motor',
    battery: '12V 100Ah (Set of 4 Batteries)',
    chargingTime: '6 to 7 Hours',
    charger: '48V 10A',
    material: 'MS & Stainless Steel with Weatherproof Cabin',
    range: '90 to 100 km per charge',
    speed: '30 km/h',
    idealFor: 'Mobile citizen services, CSC center on wheels, ticket counters & mobile inspection units.',
    idealForMr: 'नागरी सेवा केंद्र, फिरते महा-ई-सेवा केंद्र, तिकीट खिडकी आणि तपासणी कक्ष.',
    badge: 'Unique Mobile Office'
  }
];

export const PRODUCTS_CATALOG: ProductItem[] = [
  {
    id: 'sanitary-vending-machine',
    name: 'Sanitary Napkin Vending Machine',
    nameMr: 'सॅनिटरी नॅपकीन व्हेंडींग मशीन',
    category: 'hygiene',
    categoryLabel: "Women's Hygiene",
    categoryLabelMr: 'महिला स्वच्छता व आरोग्य',
    shortDesc: 'Automated, multi-coin operated sanitary pad dispensing unit for schools, colleges & public spaces.',
    shortDescMr: 'शाळा, महाविद्यालये आणि सार्वजनिक स्वच्छतागृहांसाठी स्वयंचलित व कॉइन-ऑपरेटेड पॅड मशीन.',
    description: 'Engineered as part of Clean India / Hy-giene range to address menstrual health needs with maximum dignity, confidentiality, and convenience. Uses premium grade materials with modern equipment matching international standards. Easily installed inside washrooms.',
    descriptionMr: 'स्वच्छ भारत अभियानांतर्गत शाळा, महाविद्यालये व कार्यालयातील महिला व विद्यार्थिनींसाठी सुलभ व तत्पर सॅनिटरी पॅड उपलब्ध करून देणारे स्वयंचलित मशीन. विविध कॉइन स्वीकारण्याची सुविधा व दीर्घ बॅटरी बॅकअप.',
    features: [
      'Low Maintenance & High Durability',
      'Reliable Coin Acceptor Mechanism (Multiple coin acceptor module)',
      'Standby Power / Battery Backup System',
      'Wall Mountable & Sleek Space-Saving Footprint',
      'Mechanical and Electronic Anti-theft Locking System',
      'Compliant with 2014 Govt. Policy & Maharashtra GR 2015'
    ],
    featuresMr: [
      'अत्यंत कमी देखभाल आणि दीर्घायुष्य रचना',
      'मल्टिपल कॉइन ॲक्सेप्टर मॉड्यूल (नाणे स्वीकार प्रणाली)',
      'स्टँडबाय पॉवर बॅकअप सुविधा',
      'भिंतीवर सहज बसवता येणारी कॉम्पॅक्ट डिझाईन',
      'सुरक्षित कुलूपबंद कॅबिनेट',
      'शासकीय जी.आर. २०१५ व महिला आयोग मार्गदर्शक तत्त्वांचे पालन'
    ],
    modelsOrCapacities: ['Small 25 Easy Model', 'Economy 50 Pads Model', 'Large 100 Pads Model'],
    imagePlaceholderCategory: 'vending',
    popular: true,
    governmentApproved: true
  },
  {
    id: 'sanitary-napkin-destroyer',
    name: 'Sanitary Napkin Destroyer (Incinerator)',
    nameMr: 'सॅनिटरी नॅपकीन डिस्ट्रॉयर (इन्सिनेरेटर)',
    category: 'hygiene',
    categoryLabel: "Women's Hygiene",
    categoryLabelMr: 'महिला स्वच्छता व आरोग्य',
    shortDesc: 'Eco-friendly electric incinerator with ceramic insulation and auto thermal cutoff for toilet washrooms.',
    shortDescMr: 'सिरेमिक इन्सुलेशन आणि ऑटो थर्मल कटऑफ असलेले पर्यावरणपूरक विजेवर चालणारे भट्टी मशीन.',
    description: 'Advanced fully automated burning technology: simply open door, place napkin, and close. Wall mountable inside washrooms with advanced ceramic insulation for maximum thermal protection, safe outer surface temperature, auto power cut-off and ash tray collection.',
    descriptionMr: 'वापरलेले सॅनिटरी नॅपकिन्स तत्काळ सुरक्षितपणे जाळून राख करणारे अत्याधुनिक इन्सिनेरेटर. सिरेमिक इन्सुलेशनमुळे बाहेरील आवरण गरम होत नाही, ऑटोमॅटिक तापमान नियंत्रण व सोपा राख काढण्याचा ट्रे.',
    features: [
      'Advanced fully automated operation (just open and close)',
      'Electrically operated with minimal power consumption',
      'High grade Ceramic Insulation for excellent thermal protection',
      'Auto thermal cut-off sensor for maximum safety',
      'Very compact size - mounts directly inside toilet washroom',
      'Hygienic ash collection tray included',
      'Smoke exhaust flue pipe connector'
    ],
    featuresMr: [
      'पूर्णपणे स्वयंचलित तंत्रज्ञान - फक्त दरवाजा उघडा आणि बंद करा',
      'कमी विजेच्या वापरावर चालणारे',
      'सिरेमिक इन्सुलेशनमुळे उत्तम उष्णता संरक्षण',
      'सुरक्षिततेसाठी ऑटो थर्मल कटऑफ सेन्सर',
      'अतिशय कॉम्पॅक्ट आकार - थेट वॉशरुमच्या भिंतीवर माऊंट करता येते',
      'स्वच्छतेसाठी राख गोळा करण्याचा स्वतंत्र ॲश ट्रे'
    ],
    modelsOrCapacities: ['50 Pads Daily Capacity', 'Economy 100 Pads Model', 'Large Collector 200 Pads High-Volume'],
    imagePlaceholderCategory: 'destroyer',
    popular: true,
    governmentApproved: true
  },
  {
    id: 'sanitary-napkin-pads',
    name: 'SoftTouch Sanitary Napkin Pads',
    nameMr: 'सॉफ्टटच सॅनिटरी नॅपकीन पॅड्स',
    category: 'hygiene',
    categoryLabel: "Women's Hygiene",
    categoryLabelMr: 'महिला स्वच्छता व आरोग्य',
    shortDesc: 'Ultra-absorbent, skin-friendly, hygienic sanitary pads specially manufactured for vending machines.',
    shortDescMr: 'अल्ट्रा-ॲबसॉर्बंट, त्वचेसाठी सुरक्षित आणि व्हेंडींग मशीनसाठी अनुकूल सॅनिटरी पॅड्स.',
    description: 'High-quality cottony soft sanitary napkins specifically packed for seamless dispensing through SoftTouch vending machines. Tested for leak-lock protection, anti-bacterial hygiene, and maximum comfort during long hours.',
    descriptionMr: 'मऊ कापसाचे, उत्कृष्ट शोषण क्षमता असलेले आणि व्हेंडींग मशीनमधून सहज बाहेर पडण्यासाठी विशेष पॅकेजिंग असलेले सॅनिटरी पॅड.',
    features: [
      'Ultra absorbent core with leak protection barrier',
      'Soft breathable top layer preventing skin irritation',
      'Vending machine compatible compact packaging',
      'Individual disposal bag wrap included'
    ],
    featuresMr: [
      'गळती रोखण्यासाठी जलद शोषण क्षमता',
      'मऊ आणि हवेशीर पृष्ठभाग',
      'व्हेंडींग मशीनसाठी योग्य पॅकिंग',
      'वैयक्तिक डिस्पोजल रॅपर'
    ],
    modelsOrCapacities: ['Regular Winged Pack', 'XL Overnight Extra Absorbency', 'Bulk Institutional Supplies (1000+ Units)'],
    imagePlaceholderCategory: 'pads',
    governmentApproved: true
  },
  {
    id: 'feedback-monitoring-system',
    name: 'Toilet Feedback Monitoring System',
    nameMr: 'टॉयलेट फिडबॅक मॉनिटरी सिस्टीम (स्वच्छता मॉनिटर)',
    category: 'facility',
    categoryLabel: 'Facility & Smart Governance',
    categoryLabelMr: 'सुविधा व ई-प्रशासन',
    shortDesc: '"Is this Toilet Clean? / क्या यह शौचालय स्वच्छ है?" - 3-button touch feedback unit with real-time alerting.',
    shortDescMr: 'नागरिकांचा स्वच्छता अनुभव नोंदवणारी व तातडीने अलर्ट पाठवणारी स्मार्ट फिडबॅक प्रणाली.',
    description: 'Provides municipal corporations, public transit terminals, schools, and hospitals a convenient tool for monitoring toilet cleanliness and improving sanitation staff accountability. Visitors rate their experience (Clean, OK, Dirty) with immediate escalation alerts for maintenance.',
    descriptionMr: 'सार्वजनिक व संस्थात्मक स्वच्छतागृहांची दैनंदिन स्वच्छता राखण्यासाठी नागरिकांचा अभिप्राय नोंदवणारी यंत्रणा. स्वच्छ, ठीक, अस्वच्छ अशी बटणे असून अस्वच्छतेची नोंद होताच स्वच्छता निरीक्षकाला अलर्ट मिळतो.',
    features: [
      'Interactive 3-level smiley feedback console',
      'Prominent multilingual display (English / Hindi / Marathi)',
      'Instant supervisor alert on negative feedback',
      'Robust tamper-resistant and water-resistant casing',
      'Cloud analytics & reporting dashboard'
    ],
    featuresMr: [
      'आकर्षक ३ स्मायली बटण पॅनेल',
      'ठळक बहुभाषिक फलक (इंग्रजी, हिंदी, मराठी)',
      'अस्वच्छ शेरा नोंदवल्यास त्वरित स्वच्छता पथकाला मेसेज',
      'वॉटरप्रुफ व मजबूत केसिंग',
      'तपशीलवार दैनिक व मासिक स्वच्छता अहवाल'
    ],
    modelsOrCapacities: ['On-line Cloud Feedback System (GSM/WiFi)', 'Off-line Standalone Feedback System (Local Logger)'],
    imagePlaceholderCategory: 'feedback',
    popular: true,
    governmentApproved: true
  },
  {
    id: 'weight-bridge-machine',
    name: 'Weight Bridge Machine (Truck Scale & भुईकाटा)',
    nameMr: 'वेट ब्रिज मशीन (ट्रक स्केल व भुईकाटा)',
    category: 'weighbridge',
    categoryLabel: 'Industrial Scales',
    categoryLabelMr: 'औद्योगिक वजनकाटा',
    shortDesc: 'Heavy-duty performance electronic truck scale weighbridges, tank weighing & onboard weighing systems.',
    shortDescMr: 'अवजड वाहनांसाठी उच्च अचूकतेचे इलेक्ट्रॉनिक वे-ब्रिज, ट्रक स्केल व टँक वेईंग यंत्रणा.',
    description: 'Plays a vital role in modern industrial, agricultural, and logistics hubs by delivering accurate weight data for incoming and outgoing haulage vehicles. Integrated with versatile digital instrumentation, user-friendly weighing software, printer interface, and cloud reporting.',
    descriptionMr: 'एमआयडीसी, साखर कारखाने, कृषी उत्पन्न बाजार समित्या, खाणी आणि गोदामांसाठी अचूक वजन मोजणारे कॉम्प्युटराइज्ड भुईकाटे. संपूर्ण डेटा संकलन व आधुनिक सॉफ्टवेअर कनेक्टिव्हिटी.',
    features: [
      'High precision digital load cells with lightning protection',
      'Pit / Pitless & Mobile Foundation designs',
      'Heavy-duty anti-skid MS deck platform',
      'Intelligent software with camera integration and slip generation',
      'High overload safety factor'
    ],
    featuresMr: [
      'विजेच्या धक्क्यापासून सुरक्षित हाय-प्रिसिजन लोड सेल्स',
      'पिट आणि पिटलेस दोन्ही प्रकारात उपलब्ध',
      'मजबूत अँटी-स्किड स्टील प्लॅटफॉर्म',
      'सॉफ्टवेअर, कॅमेरा आणि प्रिंट पावती कनेक्टिव्हिटी',
      'अतिरिक्त भार सहन करणारी मजबूत रचना'
    ],
    modelsOrCapacities: ['Small 20 Ton Model', 'Medium 40 Ton Model', 'Large 60 Ton Model', 'Heavy Duty 80 to 100 Ton Custom Scale'],
    imagePlaceholderCategory: 'weighbridge',
    popular: true
  },
  {
    id: 'plastic-baling-machine',
    name: 'Plastic Bailing Machine (Hydraulic Baling Press)',
    nameMr: 'प्लास्टीक बेलिंग मशीन (हायड्रॉलिक बेलर)',
    category: 'waste',
    categoryLabel: 'Waste Management',
    categoryLabelMr: 'कचरा व्यवस्थापन व पुनर्वापर',
    shortDesc: 'Hydraulic compression press for compacting scrap plastics, pet bottles, and cardboard into dense bales.',
    shortDescMr: 'प्लॅस्टिक बाटल्या, वेस्ट कागद आणि भंगार कॉम्पॅक्ट ब्लॉक्समध्ये दाबणारे हायड्रॉलिक मशीन.',
    description: 'Normally used to bale unused and scrap plastics into manageable, high-density blocks including pet bottles, cans, paper, and toys. Drastically reduces transport volume, prevents environmental contamination, and unlocks commercial salvage revenue for recycling businesses.',
    descriptionMr: 'प्लॅस्टिकच्या रिकाम्या बाटल्या, खेळणी, कार्टन बॉक्स कॉम्पॅक्ट करून वाहतूक खर्च ९०% पर्यंत कमी करणारे हायड्रॉलिक बेलिंग मशीन. पुनर्वापर आणि कचरा व्यवस्थापनात अत्यंत फायदेशीर.',
    features: [
      'Powerful hydraulic ram with hardened guides',
      'Auto bale ejector mechanism for quick discharge',
      'Rugged structural frame engineered for 24x7 industrial shifts',
      'Simple dual lever / push-button electrical panel',
      'Low power hydraulic pump with safety relief valves'
    ],
    featuresMr: [
      'मजबूत हायड्रॉलिक सिलेंडर व पंप यंत्रणा',
      'तयार झालेली गाठ (बेल) बाहेर ढकलण्यासाठी ऑटो इजेक्टर',
      'सतत वापरासाठी मजबूत औद्योगिक फ्रेम',
      'सोपी कंट्रोल पॅनेल प्रणाली',
      'सुरक्षिततेसाठी ओव्हरलोड रिलीफ व्हॉल्व्ह'
    ],
    modelsOrCapacities: ['Small 20 Ton Press', 'Medium 40 Ton Press', 'Large 60 Ton Heavy Industry Press'],
    imagePlaceholderCategory: 'baling'
  },
  {
    id: 'waste-composting-machine',
    name: 'Organic Waste Composting Machine',
    nameMr: 'कचरा खत निर्मिती मशीन (वेस्ट कंपोस्टींग मशीन)',
    category: 'waste',
    categoryLabel: 'Waste Management',
    categoryLabelMr: 'कचरा व्यवस्थापन व पुनर्वापर',
    shortDesc: 'Converts wet kitchen, canteen, and market organic waste into pathogen-free nutrient-rich manure.',
    shortDescMr: 'ओल्या कचऱ्यापासून २४ ते ४८ तासांत उच्च प्रतीचे सेंद्रिय खत तयार करणारे कॉम्पॅक्ट मशीन.',
    description: 'Fully automated organic waste converter utilizing high-temperature aerobic digestion and internal shredding blades to transform segregated wet waste into natural organic compost within hours. Ideal for municipal wards, large housing societies, vegetable markets, and hostels.',
    descriptionMr: 'महानगरपालिका, भाजी मंडई, हॉटेल्स व मोठ्या सोसायट्यांसाठी ओल्या कचऱ्यावर प्रक्रिया करून दर्जेदार खत निर्माण करणारे स्वयंचलित मशीन.',
    features: [
      'Odour-free operation with activated carbon exhaust filter',
      'High grade stainless steel SS304 internal chamber',
      'Microprocessor temperature and moisture control',
      'Volume reduction of organic waste up to 85-90%'
    ],
    featuresMr: [
      'दुर्गंधीमुक्त ऑपरेशन (कार्बन फिल्टरसह)',
      'गंजरोधक स्टेनलेस स्टील (SS304) आतील चेंबर',
      'स्वयंचलित तापमान व आर्द्रता नियंत्रण',
      'कचऱ्याचे प्रमाण ८५ ते ९० टक्क्यांपर्यंत कमी करते'
    ],
    modelsOrCapacities: ['50 kg/day Society Model', '100 kg/day Commercial Model', '250 to 500 kg/day Municipal Ward Plant'],
    imagePlaceholderCategory: 'compost',
    governmentApproved: true
  },
  {
    id: 'shredder-machine',
    name: 'Industrial Heavy Duty Shredder Machine',
    nameMr: 'औद्योगिक श्रेडर मशीन',
    category: 'waste',
    categoryLabel: 'Waste Management',
    categoryLabelMr: 'कचरा व्यवस्थापन व पुनर्वापर',
    shortDesc: 'Dual-shaft robust cutting shredder for plastic lumps, paper, cans, e-waste, and municipal scrap.',
    shortDescMr: 'प्लॅस्टिक, पुठ्ठा, धातूचे कॅन्स आणि घरातील सुक्या कचऱ्याचे बारीक तुकडे करणारे मशीन.',
    description: 'High torque rotary blade shredding unit designed to crush and slice bulky solid waste materials prior to baling, sorting, or pyrolysis processing. Features hardened alloy steel blades and automatic reverse gear against jams.',
    descriptionMr: 'कचरा वर्गीकरण आणि पुनर्वापरापूर्वी विविध प्रकारच्या घनकचऱ्याचे बारीक तुकडे करण्यासाठी वापरले जाणारे शक्तिशाली श्रेडर मशीन.',
    features: [
      'Dual shaft alloy steel hardened rotary cutters',
      'Automatic PLC anti-jam reverse rotation mechanism',
      'Heavy gearbox for maximum torque at low RPM',
      'Safety emergency stop controls on feeding hopper'
    ],
    featuresMr: [
      'अत्यंत मजबूत अ‍ॅलॉय स्टील कटर ब्लेड्स',
      'कचरा अडकल्यास स्वयंचलित रिव्हर्स रोटेशन',
      'कमी वेगात जास्त ताकद देणारे हेवी गिअरबॉक्स',
      'आणीबाणीच्या वेळी तत्काळ थांबणारे इमर्जन्सी स्विच'
    ],
    modelsOrCapacities: ['5 HP Single Shaft Compact', '10 HP Dual Shaft Standard', '20 HP Industrial Scrap Shredder'],
    imagePlaceholderCategory: 'shredder'
  },
  {
    id: 'screening-conveyor',
    name: 'Screening Machine with Conveyor Belt',
    nameMr: 'स्किर्नींग मशीन विथ कन्व्हेयर बेल्ट (कचरा वर्गीकरण)',
    category: 'waste',
    categoryLabel: 'Waste Management',
    categoryLabelMr: 'कचरा व्यवस्थापन व पुनर्वापर',
    shortDesc: 'Automated trommel / vibratory screening separator equipped with variable speed conveyor belt.',
    shortDescMr: 'महानगरपालिका कचरा डेपो व प्रकल्पांसाठी बेल्ट कन्व्हेयरसह कचरा चाळणी व वर्गीकरण मशीन.',
    description: 'Built for municipal dumping grounds, bio-mining legacy waste reclamation, and compost sorting lines. The rotating trommel/screen separates fine organic manure, intermediate gravel, and coarse non-biodegradable plastics seamlessly along the conveyor feed.',
    descriptionMr: 'घनकचरा व्यवस्थापन प्रकल्पांमध्ये विविध आकारांचा कचरा, माती, खत आणि प्लॅस्टिक वेगळे करण्यासाठी कन्व्हेयर बेल्टसह कार्यरत असणारी चाळणी यंत्रणा.',
    features: [
      'Variable mesh size interchangeable rotary screen (Trommel)',
      'Heavy rubberized continuous cleated conveyor belt',
      'Adjustable feed rate hopper',
      'Mobile wheeled chassis option for easy relocation on site'
    ],
    featuresMr: [
      'विविध आकाराच्या जाळ्या बदलण्याची सोय',
      'हेव्ही ड्युटी रबरी कन्व्हेयर बेल्ट',
      'कचरा टाकण्यासाठी मोठा हॉपर',
      'एका ठिकाणाहून दुसऱ्या ठिकाणी नेण्यासाठी व्हील चेसिस'
    ],
    modelsOrCapacities: ['5 TPH Screening Line', '10 TPH Municipal Plant', 'Custom Bio-Mining Plants'],
    imagePlaceholderCategory: 'conveyor',
    governmentApproved: true
  },
  {
    id: 'fire-safety',
    name: 'Fire Extinguishers & Fire Extinguisher Balls',
    nameMr: 'फायर इस्टंग्युशर व ऑटोमॅटिक फायर बॉल',
    category: 'safety',
    categoryLabel: 'Safety Equipment',
    categoryLabelMr: 'अग्निशमन व सुरक्षा',
    shortDesc: 'ISI certified ABC powder, CO2 extinguishers and revolutionary auto-activating fire extinguisher balls.',
    shortDescMr: 'आयएसआय मानांकित फायर एक्स्टिंग्युशर आणि आग लागताच अवघ्या ३ सेकंदात फुटणारा ऑटो फायर बॉल.',
    description: 'Crucial emergency protection systems for public buildings, schools, factories, and commercial vehicles. Features revolutionary lightweight fire extinguishing balls that automatically activate within 3-5 seconds of contact with flame, dispersing extinguishing dry powder over 360 degrees.',
    descriptionMr: 'शाळा, महाविद्यालये, फॅक्टरी आणि वाहनांसाठी अत्यावश्यक अग्निशामक उपकरणे. आगीच्या संपर्कात येताच ३ ते ५ सेकंदात आपोआप सक्रिय होणारा आधुनिक फायर बॉल.',
    features: [
      'Self-activating fire ball with loud alert blast (120dB)',
      'Safe non-toxic chemical powder dispersion (Class A, B, C & Electrical)',
      'Zero maintenance, 5-year shelf life for fire balls',
      'Standard portable 2kg, 4kg, 6kg, 9kg DCP and CO2 cylinders'
    ],
    featuresMr: [
      'आग लागताच ३-५ सेकंदात आपोआप फुटणारा फायर बॉल',
      'सर्व प्रकारच्या आगींवर (A, B, C व इलेक्ट्रिक) प्रभावी',
      'कोणत्याही देखभालीशिवाय ५ वर्षे सुरक्षित',
      '२ किलो, ४ किलो, ६ किलो क्षमतेचे प्रमाणित सिलिंडर्स'
    ],
    modelsOrCapacities: ['1.3 kg Auto Fire Extinguisher Ball', '4 kg / 6 kg ABC Dry Powder Extinguisher', '4.5 kg CO2 Gas Fire Cylinder'],
    imagePlaceholderCategory: 'fire'
  },
  {
    id: 'water-ro-plant',
    name: 'Industrial RO & Water Filtration Systems',
    nameMr: 'औद्योगिक आरओ प्लांट व वॉटर फिल्टर सिस्टीम',
    category: 'facility',
    categoryLabel: 'Facility & Water Systems',
    categoryLabelMr: 'पाणी शुद्धीकरण यंत्रणा',
    shortDesc: 'Commercial and institutional RO water purification plants with dual sand and carbon filter columns.',
    shortDescMr: 'शाळा, महाविद्यालये आणि कारखान्यांसाठी उच्च क्षमतेचे आरओ वॉटर फिल्टरेशन प्लॅन्ट्स.',
    description: 'As demonstrated in SoftTouch manufacturing installations, multi-stage water filtration columns with high-pressure booster pumps, stainless steel control skids, and reverse osmosis membrane vessels ensure clean, safe drinking water compliant with WHO and BIS standards.',
    descriptionMr: 'हॉटेल्स, शैक्षणिक संस्था आणि कारखान्यांसाठी सँड व कार्बन फिल्टरसह पिण्याचे पाणी १००% शुद्ध करणारे आरओ वॉटर सिस्टीम.',
    features: [
      'Dual pressure sand & activated carbon filtration vessels',
      'High rejection TFC reverse osmosis membranes',
      'Digital TDS and flow rate indicators on stainless steel control panel',
      'Automatic backwash and flushing system'
    ],
    featuresMr: [
      'ड्युअल सँड व अ‍ॅक्टिव्हेटेड कार्बन फिल्टर स्तंभ',
      'उच्च दर्जाचे टीएफसी रिव्हर्स ऑस्मोसिस मेम्ब्रेन',
      'डिजिटल टीडीएस आणि फ्लो मीटरसह स्टेनलेस स्टील पॅनेल',
      'स्वयंचलित फ्लशिंग व बॅकवॉश यंत्रणा'
    ],
    modelsOrCapacities: ['250 LPH School Plant', '500 LPH Institutional Plant', '1000 to 2000 LPH Industrial Skid'],
    imagePlaceholderCategory: 'water'
  }
];

export const MAHARASHTRA_NETWORK: BranchOffice[] = [
  { city: 'Jalgaon', cityMr: 'जळगाव', type: 'Factory', address: 'Ajantha Road, Opp. Manraj Maruti Showroom, M.I.D.C. Area', phone: '+91 9096000080', highlight: true },
  { city: 'Jalgaon (Vidyut Colony)', cityMr: 'जळगाव (विद्युत कॉलनी)', type: 'Branch Office', address: 'Plot No. 21, Vidyut Colony, Jalgaon - 425001', phone: '+91 9096000080', highlight: true },
  { city: 'Jalgaon (Shiv Colony)', cityMr: 'जळगाव (शिव कॉलनी)', type: 'Branch Office', address: 'Plot No. 15, Shiv Colony, National Highway, Jalgaon - 425001', phone: '+91 9970022077' },
  { city: 'Jalgaon (Ramanand Nagar)', cityMr: 'जळगाव (रामानंद नगर)', type: 'Registered Office', address: 'Plot No. 13, Beside Puja Apt, Near Girna Taki, Ramanand Nagar Rd', phone: '+91 9096000080' },
  { city: 'Jalgaon (Golani Market)', cityMr: 'जळगाव (गोलाणी मार्केट)', type: 'Commercial Office', address: 'D-28, 2nd Floor, Golani Market, Jalgaon - 425001', phone: '+91 9970022077' },
  { city: 'Dhule', cityMr: 'धुळे', type: 'Service Network', address: 'North Maharashtra Regional Service Hub', phone: '+91 9096000080' },
  { city: 'Nandurbar', cityMr: 'नंदुरबार', type: 'Service Network', address: 'Tribal Welfare & District Supply Coordinator', phone: '+91 9096000080' },
  { city: 'Buldhana', cityMr: 'बुलढाणा', type: 'Service Network', address: 'Vidarbha Division Liaison', phone: '+91 9096000080' },
  { city: 'Chandrapur', cityMr: 'चंद्रपूर', type: 'Service Network', address: 'Industrial & Mining Zone Service Center', phone: '+91 9096000080' },
  { city: 'Nagpur', cityMr: 'नागपूर', type: 'Service Network', address: 'Vidarbha Regional Operations Office', phone: '+91 9096000080' },
  { city: 'Kolhapur', cityMr: 'कोल्हापूर', type: 'Service Network', address: 'South Maharashtra Industrial Corridor', phone: '+91 9096000080' },
  { city: 'Solapur', cityMr: 'सोलापूर', type: 'Service Network', address: 'Textile & Municipal Equipment Service', phone: '+91 9096000080' },
  { city: 'Akola', cityMr: 'अकोला', type: 'Service Network', address: 'Central Vidarbha Distribution Network', phone: '+91 9096000080' },
  { city: 'Sangli', cityMr: 'सांगली', type: 'Service Network', address: 'Agro & Industrial Weighbridge Hub', phone: '+91 9096000080' },
  { city: 'Amravati', cityMr: 'अमरावती', type: 'Service Network', address: 'Regional Educational Equipment Liaison', phone: '+91 9096000080' },
  { city: 'Ratnagiri', cityMr: 'रत्नागिरी', type: 'Service Network', address: 'Konkan Coast Municipal & Tourism Supply', phone: '+91 9096000080' },
  { city: 'Aurangabad (Chh. Sambhajinagar)', cityMr: 'छत्रपती संभाजीनगर (औरंगाबाद)', type: 'Service Network', address: 'Marathwada Divisional Hub', phone: '+91 9096000080' },
  { city: 'Ahmednagar', cityMr: 'अहमदनगर', type: 'Service Network', address: 'Western Maharashtra Central Point', phone: '+91 9096000080' },
  { city: 'Nashik', cityMr: 'नाशिक', type: 'Service Network', address: 'MIDC & Northern Maharashtra Service Unit', phone: '+91 9096000080' },
  { city: 'Pune', cityMr: 'पुणे', type: 'Service Network', address: 'Automotive & Institutional Sales Hub', phone: '+91 9096000080' },
  { city: 'Mumbai', cityMr: 'मुंबई', type: 'Service Network', address: 'Metropolitan & Govt. Tender Directorate', phone: '+91 9096000080' },
  { city: 'Kalyan', cityMr: 'कल्याण', type: 'Service Network', address: 'Thane & MMR Regional Service Center', phone: '+91 9096000080' }
];

export const SOCIAL_INITIATIVES = {
  titleEn: "Social Mission & Government Policy Alignment",
  titleMr: "सामाजिक बांधिलकी व शासकीय योजनांचा पाठपुरावा",
  introEn: "SoftTouch was established with a deep social mission: to alleviate the challenges faced by women and young girls during menstruation, and to empower municipalities with modern waste management and clean mobility technology.",
  introMr: "महिला आणि मुलींना होणाऱ्या मासिकपाळीच्या त्रासात मदत करणे व जनजागृती निर्माण करणे हे कंपनीचे मुख्य उद्दिष्ट आहे. सॅनिटरी नॅपकीन व्हेंडींग मशीन व डिस्ट्रॉयर ही दोन मशीन शहरी तसेच ग्रामीण भागात महिला आरोग्याची ही समस्या सोडविण्यासाठी आम्ही सदैव तत्पर असतो.",
  points: [
    {
      titleEn: "Government Policy 2014 Compliance",
      titleMr: "शासन धोरण २०१४",
      descEn: "Under the 2014 Government of India policy, providing sanitary pads to women and schoolgirls in educational and public environments is an institutional priority.",
      descMr: "शासन धोरण २०१४ मध्ये महिला व मुलींकरीता सॅनिटरी पॅड उपलब्ध करून देणे हे शासनाचे कर्तव्य व अग्रक्रम ठरविले आहे."
    },
    {
      titleEn: "Swachh Bharat Abhiyan Scoring",
      titleMr: "स्वच्छ भारत अभियान सहकार्य",
      descEn: "Under the national Swachh Bharat Abhiyan ranking, installation of sanitary napkin vending machines, eco-incinerators, and public toilet feedback monitors directly earns marks for municipal corporations.",
      descMr: "स्वच्छ भारत अभियानांतर्गत देखील या दोन्ही मशिनची आवश्यकता आपल्या महानगरपालिकेला गुणांकनाकरिता अत्यावश्यक आहे."
    },
    {
      titleEn: "Govt GR 2015 & Maharashtra Women's Commission Directive",
      titleMr: "शासकीय जी.आर. २०१५ व महिला आयोग",
      descEn: "Mandated for all schools, colleges, and polytechnics under Govt. GR 2015. The Maharashtra State Women's Commission regularly follows up and mandates these machines across institutions.",
      descMr: "सर्व शाळा व महाविद्यालये तसेच शासकीय तंत्रनिकेतने जी.आर. क्रमांक २०१५ नुसार महिला आयोगाने देखील ही मशीन बसविणे बंधनकारक केले आहे व ते पाठपुरावा करतात."
    },
    {
      titleEn: "Pan-Maharashtra Institutional Footprint",
      titleMr: "राज्यभरात हजारो संस्थांमध्ये यशस्वी उभारणी",
      descEn: "Installed and maintained in numerous municipal corporations, municipal councils (Nagar Palikas), gram panchayats, schools, colleges, and social organizations throughout Maharashtra and India.",
      descMr: "आजतागायत कंपनीने अनेक नगरपालिका, ग्रामपंचायत, शाळा, महाविद्यालये तसेच विविध संस्थांच्या मार्फत राज्यभरात व संपूर्ण देशभरात मशनरी बसविली आहेत."
    }
  ]
};

export const TRANSLATIONS = {
  en: {
    navAbout: 'About Us',
    navProducts: 'Products & Machinery',
    navEVehicles: 'E-Vehicles & Food Trucks',
    navMission: 'Social Mission',
    navCertificates: 'Certifications',
    navBranches: 'Branch Network',
    navContact: 'Contact Us',
    getQuote: 'Request Quote',
    callNow: 'Call Direct',
    isoCertified: 'AN ISO 9001:2015 Certified Company',
    gmpCertified: 'GMP & CE Compliant Manufacturer',
    heroTag: 'Govt. Approved Manufacturer of Modern Machinery & Clean Mobility',
    heroTitle: 'Touch of Modern Technology for Sanitation, Green Mobility & Industry',
    heroSubtitle: 'From automated sanitary vending & incinerators supporting Swachh Bharat Abhiyan to powerful commercial electric carts, weighbridges, and baling presses — empowering Maharashtra & India since 2016.',
    heroCta1: 'Explore Machinery',
    heroCta2: 'View Certifications',
    heroStat1: 'Years of Engineering',
    heroStat2: 'Workforce & Technicians',
    heroStat3: 'District Network Hubs',
    heroStat4: 'Govt. Compliance Licenses',
    filterAll: 'All Machineries',
    filterHygiene: "Women's Hygiene",
    filterVehicles: 'Electric E-Carts',
    filterWaste: 'Waste & Recycling',
    filterWeighbridge: 'Weighbridges',
    filterFacility: 'Facility Systems',
    quickSpec: 'Key Specifications',
    features: 'Salient Features',
    availableModels: 'Standard Models & Capacities',
    inquireAboutProduct: 'Inquire About This Machine',
    closeModal: 'Close',
    eCartBenefitsTitle: 'Why Choose SoftTouch E-Cart for Your Business?',
    eCartBenefit1Title: 'Low Investment, High Profit',
    eCartBenefit1Desc: 'कमी खर्चात जास्त उत्पन्न - Save lakhs compared to fuel-run autos with almost zero daily running cost.',
    eCartBenefit2Title: 'Ultra Low Maintenance',
    eCartBenefit2Desc: 'कमी देखभाल - Rugged Indian chassis with readily available local spares and direct factory support.',
    eCartBenefit3Title: 'Heavy Payload & Power',
    eCartBenefit3Desc: 'शक्तिशाली वाहन - High torque 48V/60V DC motors tackling 200kg to 600kg payloads seamlessly.',
    specsCompareTitle: 'Electric Commercial Vehicle Specifications',
    certTitle: 'Quality Certifications & Statutory Documentation',
    certSubtitle: 'Authentic government registrations, ISO 9001:2015, CE compliance, trademark and GST records.',
    verified: 'Verified & Active',
    networkTitle: 'Our Network Across Maharashtra & India',
    networkSubtitle: 'Headquartered in Jalgaon with factory, branch offices, and active operational service hubs covering 18+ districts.',
    contactTitle: 'Get in Touch with Our Engineering Team',
    contactSubtitle: 'Need customized dimensions, institutional bulk orders, or municipal tenders? Speak directly with Prof. Uday Yeshe.',
    contactFormName: 'Your Full Name',
    contactFormPhone: 'Phone / WhatsApp Number',
    contactFormCity: 'Your City / District',
    contactFormProduct: 'Interested Product / Machinery',
    contactFormNotes: 'Requirement Details / Quantity',
    sendInquiryWhatsApp: 'Send Inquiry via WhatsApp',
    sendInquiryCall: 'Direct Helpline Call',
    downloadProfile: 'Download / Print Company Profile'
  },
  mr: {
    navAbout: 'आमच्याविषयी',
    navProducts: 'मशनरी व उत्पादने',
    navEVehicles: 'ई-वाहन व फूड ट्रक्स',
    navMission: 'सामाजिक उद्दिष्ट',
    navCertificates: 'प्रमाणपत्रे',
    navBranches: 'शाखा व संपर्क',
    navContact: 'चौकशी करा',
    getQuote: 'कोटेशन मागवा',
    callNow: 'थेट संपर्क करा',
    isoCertified: 'आयएसओ ९००१:२०१५ प्रमाणित कंपनी',
    gmpCertified: 'जीएमपी व सीई अनुपालन उत्पादक',
    heroTag: 'आधुनिक तंत्रज्ञानाचे उत्पादक व कंत्राटदार',
    heroTitle: 'महिला आरोग्य, हरित वाहतूक आणि आधुनिक मशनरीचे विश्वासार्ह दालन',
    heroSubtitle: 'स्वच्छ भारत अभियानांतर्गत सॅनिटरी नॅपकीन व्हेंडींग व डिस्ट्रॉयर मशीन, पर्यावरणपूरक व्यावसायिक ई-वाहन (फूड ट्रक्स), भुईकाटा व घनकचरा व्यवस्थापन मशनरीचे अधिकृत उत्पादक.',
    heroCta1: 'मशनरी पहा',
    heroCta2: 'प्रमाणपत्रे तपासा',
    heroStat1: 'वर्षांची अखंड सेवा',
    heroStat2: 'कर्मचारी व तंत्रज्ञ',
    heroStat3: 'जिल्हा शाखा नेटवर्क',
    heroStat4: 'शासकीय परवाने व प्रमाणपत्रे',
    filterAll: 'सर्व मशनरी',
    filterHygiene: 'महिला स्वच्छता',
    filterVehicles: 'ई-वाहन (ई-कार्ट)',
    filterWaste: 'कचरा व्यवस्थापन',
    filterWeighbridge: 'भुईकाटा (वेब्रिज)',
    filterFacility: 'स्मार्ट सुविधा',
    quickSpec: 'महत्त्वाचे तपशील',
    features: 'प्रमुख वैशिष्ट्ये',
    availableModels: 'उपलब्ध मॉडेल्स व क्षमता',
    inquireAboutProduct: 'या मशीनबद्दल चौकशी करा',
    closeModal: 'बंद करा',
    eCartBenefitsTitle: 'आपल्या व्यवसायासाठी सॉफ्टटच ई-वाहन का निवडावे?',
    eCartBenefit1Title: 'कमी खर्चात जास्त उत्पन्न',
    eCartBenefit1Desc: 'पेट्रोल-डिझेल वाहनांच्या तुलनेत दररोज शेकडो रुपयांची बचत आणि अधिक नफा.',
    eCartBenefit2Title: 'कमी देखभाल',
    eCartBenefit2Desc: 'मजबूत भारतीय बनावट आणि जलद फॅक्टरी सर्व्हिस सपोर्ट.',
    eCartBenefit3Title: 'शक्तिशाली वाहन',
    eCartBenefit3Desc: '४८V/६०V क्षमतेच्या पॉवरफुल मोटर्स ज्या सहजपणे २०० ते ६०० किलो माल वाहून नेतात.',
    specsCompareTitle: 'ई-वाहन (इलेक्ट्रिक कार्ट) सविस्तर तांत्रिक तपशील',
    certTitle: 'कंपनी प्रमाणपत्रे व शासकीय नोंदणी सूची',
    certSubtitle: 'अधिकृत शासकीय परवाने, आयएसओ ९००१:२०१५, सीई, जीएमपी, ट्रेडमार्क व जीएसटी नोंदणी.',
    verified: 'प्रमाणित व सक्रिय',
    networkTitle: 'महाराष्ट्रभर कार्यरत शाखा व सर्व्हिस नेटवर्क',
    networkSubtitle: 'जळगाव मुख्य फॅक्टरी, नोंदणीकृत कार्यालये व महाराष्ट्रातील १८+ प्रमुख जिल्ह्यांमध्ये विस्तारलेले नेटवर्क.',
    contactTitle: 'थेट संपर्क साधा अथवा कोटेशन मिळवा',
    contactSubtitle: 'नगरपालिका, शाळा, महाविद्यालये अथवा खाजगी व्यवसायासाठी आजच संपर्क साधा.',
    contactFormName: 'आपले पूर्ण नाव',
    contactFormPhone: 'फोन / व्हॉट्सॲप नंबर',
    contactFormCity: 'आपले शहर / जिल्हा',
    contactFormProduct: 'आवश्यक मशनरी निवडा',
    contactFormNotes: 'इतर माहिती / आवश्यक संख्या',
    sendInquiryWhatsApp: 'व्हॉट्सॲपवर माहिती पाठवा',
    sendInquiryCall: 'थेट फोन करा',
    downloadProfile: 'कंपनी प्रोफाईल प्रिंट / सेव्ह करा'
  }
};
